src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="text")
     */
    private $body_short;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_url;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getBodyShort(): ?string
    {
        return $this->body_short;
    }

    public function setBodyShort(string $body_short): self
    {
        $body_short = mb_substr($body_short, 0, 200);

        $this->body_short = $body_short;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Repository\NewsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NewsController extends AbstractController
{
    /**
     * @Route("/", name="news_list")
     * @param NewsRepository $newsRepository
     * @return Response
     */
    public function index(NewsRepository $newsRepository): Response
    {
        $news = $newsRepository->findAll();
        return $this->render('news/index.html.twig', [
            'news' => $news,
        ]);
    }

    /**
     * @Route("/news/{id}", name="news_details")
     * @param NewsRepository $newsRepository
     * @param int $id
     * @return Response
     */
    public function newsDetails(NewsRepository $newsRepository, int $id): Response
    {
        $news = $newsRepository->find($id);
        return $this->render('news/newsDetails.html.twig', [
            'news' => $news,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    News list
{% endblock %}

{% block body %}

    {% for news in news %}
        <a href="{{ path('news_details', {'id':news.id}) }}">
            <h3>
                {{ news.title }}
            </h3>
            <br>
            {{ news.bodyShort ~ '. . .' }}
        </a>
    {% endfor %}

{% endblock %}

templates/news/newsDetails.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    News details
{% endblock %}

{% block body %}

    <style>
        .image {
            width: 10em;
        }
    </style>
    <div><p>{{ news.title }}</p></div>
    <div><img src="{{ news.imageUrl }}" class="image"/></div>
    <div>{{ news.body }}</div>

{% endblock %}